version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    groups:
      gomod:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - go
      - no-bump-version
    schedule:
      interval: weekly
    reviewers:
      - pacificporter/developers
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - github_actions
      - no-bump-version
    schedule:
      interval: daily
    reviewers:
      - pacificporter/developers
