version: "2"
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errchkjson
    - errorlint
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocyclo
    - gosmopolitan
    - loggercheck
    - makezero
    - musttag
    - nilerr
    - nilnesserr
    - protogetter
    - reassign
    - recvcheck
    - spancheck
    - testifylint
    - zerologlint
  disable:
    - asciicheck
    - exhaustive
    - gosec
    - noctx
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - unparam
  settings:
    errcheck:
      exclude-functions:
        - fmt:.*,^Close|^Write|^Shutdown
    gocyclo:
      min-complexity: 25
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
