name: reviewdog/action-actionlint
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          level: warning
          filter_mode: nofilter
          reporter: github-pr-review
          fail_on_error: true
