name: CI

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

env:
  TZ: "Asia/Tokyo"

jobs:
  go-build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: go.mod

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
          key: ${{ runner.os }}-cache-go-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-cache-go-build-

      - name: Go build
        run: go build ./...

      - name: Go Vet
        run: go vet ./...

      - name: Go test
        env:
          ENVIRONMENT: test
        run: go test -p=1 ./...
