name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  go:
    uses: pacificporter/github-actions/.github/workflows/go.yml@main
    with:
      tz: Asia/Tokyo
