name: CI

on:
  push:
    branches:
      - 'feature/wip-ci-with-github-actions'

jobs:
  go-build-and-test:
    uses: pacificporter/github-actions/.github/workflows/go.yml@main
    with:
      tz: "Asia/Tokyo"
